apiVersion: v1
kind: Service
metadata:
  name: prostate-cancer-service
spec:
  selector:
    app: prostate-cancer
  ports:
    - protocol: TCP
      port: 5001       # The port exposed externally
      targetPort: 5001  # The port your Flask app is running on inside the container
      nodePort: 30007  # NodePort range: 30000-32767
  type: NodePort
